### ISSUE TITLE
Build fails on Mac OS X 10.11.3

### ISSUE THREAD

**Issue by nicost** [kaspermarstal/SimpleElastix#11]
Builds of ITK and SimpleITK succeed, but building PCRE fails with error below.  Strangely enough, that is the same error I got (but much earlier on in the build) when using an out of date version of the XCode build tools.  I guess that something in the cmake instructions for PCRE is out of whack.  Anyone any ideas (or have binaries available that I could use on the Max OS X)?

checking whether we are cross compiling... configure: error: in `/Users/nico/git/SimpleElastix/build/PCRE-prefix/src/PCRE-build':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
[ 28%] Performing build step for 'PCRE'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [PCRE-prefix/src/PCRE-stamp/PCRE-build] Error 2
make[1]: *** [CMakeFiles/PCRE.dir/all] Error 2
make: *** [all] Error 2

**Comment by kaspermarstal** [comment]
Hi nicost, you can try [this solution](http://simpleelastix.readthedocs.org/GettingStarted.html#pcre-perl-compatible-regular-expression-build-fails-on-mac-os-x) in the docs. Let me know how it goes.

**Comment by nicost** [comment]
Thanks!  Convincing cmake to use clang did the trick.  Sorry for not noticing/finding the trouble shooting section (which I also needed to deal with the ssl certificate error).

**Comment by kaspermarstal** [comment]
No problem! Glad your issues have been solved. Happy coding :grin:
