### ISSUE TITLE
Groupwise registration

### ISSUE THREAD

**Issue by gattia** [kaspermarstal/SimpleElastix#14]
Hi Everyone, 

I seem to be having issues with the Groupwise registration. I am trying to follow the instructions here (http://simpleelastix.readthedocs.org/GroupwiseRegistration.html) and keep getting an error. I have attached the code I am running to the end of this post. The error comes on the last line of that code. 

But the problem comes when I true to run sitk.JoinSeries(x). No matter what I turn the values of the image to I get an error that says: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SimpleITK-0.9.1.dev15-py2.7-macosx-10.6-intel.egg/SimpleITK/SimpleITK.py", line 34781, in JoinSeries
    return _SimpleITK.JoinSeries(*args)
RuntimeError: Exception thrown in SimpleITK JoinSeries: /Users/gattia/Programming/Elastix/SimpleElastix/Code/Common/include/sitkMemberFunctionFactory.hxx:196:
sitk::ERROR: Pixel type: 8-bit unsigned integer is not supported in 3D byN3itk6simple21JoinSeriesImageFilterE

The error indicates that is has to do with the pixel type, but it doesn't matter what I change it to I still get the error. I have tried UInt16/8, Int8, Float 32.... I had read somewhere about this potentially being an issue with trying to make a 4D image? But I have 4D enabled when building SimpleElastix. 

Does anyone have a suggestion on how to go about this? 

Anthony. 

os.chdir("/Users/gattia/Desktop/t2Data/atlas/atlasSPGR")

# Concatenate the ND images into one (N+1)D image
population = ['3656_ResultRaw.nrrd', '3683_ResultRaw.nrrd', '3684_ResultRaw.nrrd', '3697_ResultRaw.nrrd', '3698_ResultRaw.nrrd', '3709_ResultRaw.nrrd', '3710_ResultRaw.nrrd', '3736_ResultRaw.nrrd', '3737_ResultRaw.nrrd']
vectorOfImages = sitk.VectorOfImage()

for filename in population:
  UInt16 = sitk.Cast(sitk.ReadImage(filename), sitk.sitkUInt8)
  vectorOfImages.push_back(UInt16)
  
image = sitk.JoinSeries(vectorOfImages)

**Comment by kaspermarstal** [comment]
It seems JoinSeriesImageFilter does not have support for 4D images at all. This is a bug. Will fix it.

**Comment by kaspermarstal** [comment]
Hi gattia, JoinSeriesImageFilter should now have support for 4D images. Run `git pull` in the SimpleElastix source directory and rebuild. Let me know how it goes.

**Comment by gattia** [comment]
Thanks for the fix! That did the trick to running the JoinSeries. 

Though, I ended up having issues using it because the images have different origins and slightly different axes. Is this common? I got around it by relaxing the tolerances using these commands:  
sitk.ProcessObject.SetGlobalDefaultDirectionTolerance(1)
sitk.ProcessObject.SetGlobalDefaultCoordinateTolerance(1)

I also had to set all of the origins to the same as one of the images. I am assuming these changes aren't best practice? Your example doesn't talk about any of these problems but with using any group for MRI or other data I am assuming it would be the case. What is typical practice? 

Thanks, 

Anthony.

**Comment by kaspermarstal** [comment]
It is certainly not best practice but I do it myself all the time. I believe the issue is with the origin and direction being slightly modified as they pass through the ITK pipeline, see e.g. [this discussion on the ITK mailing list](http://www.itk.org/pipermail/insight-developers/2014-November/024088.html). You may also have to do it after elastix registration (I know I do). I usually just do

```python
resultImage.CopyInformation(fixedImage)
```
because the result image is being transformed to the fixed image domain so these should be equal anyway. The documentation could indeed be improved in this area. You are welcome to submit a PR otherwise I will do it when I get the time.

**Comment by gattia** [comment]
Thanks for the response. I will take an attempt at a pull request/edit to that portion of the document. It will be my first :). 

Anthony.

**Comment by pgranger23** [comment]
Hi !

I built SimpleElastix with the latest git version. Nonetheless I experience exactly the same issue that gattia exposed in his first message.
I hope that you will be able to help me,

Pierre

**Comment by kaspermarstal** [comment]
Did you set `SimpleITK_4D_IMAGES` to `ON`?

**Comment by pgranger23** [comment]
Yes I did.

**Comment by kaspermarstal** [comment]
What is the error message you are seeing?

**Comment by pgranger23** [comment]
I got the following error for any pixel type :
`Traceback (most recent call last):
  File "dose_tracking_pierre_2.py", line 36, in <module>
    image = sitk.JoinSeries(image_vector)
  File "/usr/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 39910, in JoinSeries
    return _SimpleITK.JoinSeries(*args)
RuntimeError: Exception thrown in SimpleITK JoinSeries: /home/pgranger/Documents/Stage_M1/SimpleElastix/Code/Common/include/sitkMemberFunctionFactory.hxx:196:
sitk::ERROR: Pixel type: 32-bit signed integer is not supported in 3D byN3itk6simple21JoinSeriesImageFilterE`

I just load 3D images and try to Join them in a 4D image.

**Comment by kaspermarstal** [comment]
Try to pull and rebuild the develop branch and let me know how it goes.

**Comment by pgranger23** [comment]
I did as you said and it perfectly solved my issue, thank you very much !
