### ISSUE TITLE
Error while building sitkSimpleElastix.cxx under Linux

### ISSUE THREAD

**Issue by talmo** [kaspermarstal/SimpleElastix#16]
OK so, I've been trying to get SimpleElastix compiling under Ubuntu 14.04 x64 and have not had much success. I've tried this on our lab computer and on a clean VirtualBox VM on different computer both running the same OS.

Here are the steps to reproduce the issue from a clean install of Ubuntu 14.04:
```
# Dependencies
sudo apt-get update
sudo apt-get install bison git subversion cmake build-essential clang-3.4

# SVN auth workaround
echo p | svn info https://svn.bigr.nl/elastix/trunkpublic/

# Download the development branch of SimpleElastix
mkdir ~/SimpleElastix && mkdir ~/SimpleElastix/build && cd ~/SimpleElastix
git clone -b develop https://github.com/kaspermarstal/SimpleElastix.git SimpleElastix

# CMake and compile
cd ~/SimpleElastix/build
cmake ../SimpleElastix/SuperBuild
make -j8
```

After a while with lots of things compiling, the build stops. The log is the top of a ~3900 line log file that gets produced if we then just resume building with `make &> error.log`:
```
[ 16%] Built target ITK
[ 32%] Built target PCRE
[ 48%] Built target Swig
[ 65%] Built target elastix
[ 67%] Performing forcebuild step for 'SimpleITK'
[ 69%] Performing build step for 'SimpleITK'
[  9%] Built target SimpleITKData
[ 10%] Built target lua5
[ 10%] Built target lua
[ 10%] Built target SimpleITKExplicit
[ 10%] Built target SimpleITKCommon
[ 10%] Building CXX object Code/Elastix/src/CMakeFiles/SimpleElastix.dir/sitkSimpleElastix.cxx.o
...
make[5]: *** [Code/Elastix/src/CMakeFiles/SimpleElastix.dir/sitkSimpleElastix.cxx.o] Error 1
make[4]: *** [Code/Elastix/src/CMakeFiles/SimpleElastix.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
```
At this point, 11 warnings and 407 errors get printed out and the build fails. [Here's the whole log file](https://gist.github.com/talmo/63a7c8c5b8cecacfa771).

This is all on the current develop commit (a4db5bc) with no further modifications.

I have no clue what could be going on. Some of the error messages have to do with some pretty basic classes not being declared, e.g.:
```
In file included from /home/wanglab/SimpleElastix/build/elastix/src/Core/Main/elxElastixFilter.h:176:0,
                 from /home/wanglab/SimpleElastix/SimpleElastix/Code/Elastix/include/sitkSimpleElastix.h:11,
                 from /home/wanglab/SimpleElastix/SimpleElastix/Code/Elastix/src/sitkSimpleElastix.cxx:4:
/home/wanglab/SimpleElastix/build/elastix/src/Core/Main/elxElastixFilter.hxx: In member function ‘void elastix::ElastixFilter<TFixedImage, TMovingImage>::GenerateData()’:
/home/wanglab/SimpleElastix/build/elastix/src/Core/Main/elxElastixFilter.hxx:83:69: error: ‘ProcessObject’ has not been declared
       duplicator->SetInputImage( static_cast< TFixedImage* >( this->ProcessObject::GetInput( inputNames[ i ] ) ) );
                                                                     ^
```

Am I missing something in this build setup? Any tips would be greatly appreciated! Thanks!

(Note: This is unrelated to #15 as I'm trying to compile on both OSes for different applications.)

**Comment by talmo** [comment]
OK so, figured it out:

1. You were correct in #15 that I was trying to compile from the `develop` branch while using an older version of elastix (the current public branch one). I switched back to `SimpleElastix` and just added in the auth for the svn.

2. It seems like there's an issue with cmake(?) or something but it was incorrectly using `cc` and `c++` instead of `gcc` and `g++` to build, so all the functions using C++11 features were failing. I fixed that by explicitly setting the compiler paths:
```
cmake -DCMAKE_CXX_COMPILER=$(which g++) -DCMAKE_C_COMPILER=$(which gcc) ../SimpleElastix-SimpleElastix/SuperBuild
make CXX=$(which g++) CC=$(which gcc) -j6
```

3. The python wrapper wasn't building. I'm using anaconda and it seems like even if the paths are set in my environment, cmake still won't pick up on them, so I ended up setting them explicitly, to yield the final calls:
```

cd ~/SimpleElastix/SimpleElastix-SimpleElastix_build/ && rm -rf * && cmake 
    -DCMAKE_CXX_COMPILER=$(which g++) 
    -DCMAKE_C_COMPILER=$(which gcc) 
    -DWRAP_PYTHON=ON 
    -DPYTHON_INCLUDE_DIR=/home/talmo/anaconda/include/python2.7/ 
    -DPYTHON_INCLUDE_DIR2=/home/talmo/anaconda/include/python2.7 
    -DPYTHON_LIBRARY=/home/talmo/anaconda/lib/libpython2.7.so 
    -DPYTHON_LIBRARY_DEBUG=/home/talmo/anaconda/lib/libpython2.7.so 
    -DPYTHON_LIBRARY_RELEASE=/home/talmo/anaconda/lib/libpython2.7.so
    ../SimpleElastix-SimpleElastix/SuperBuild

make CXX=$(which g++) CC=$(which gcc) -j6
```

Now it works :)

**Comment by JuReinhardt** [comment]
Hello,

I've tried to compiled under ubuntu 14.04 x64 as well, running into a similar error:

[...]
[ 26%] Built target ITKJPEG-all
[ 26%] Generating tif_fax3sm.c
/bin/sh: 1: ./itkmkg3states: Permission denied
make[5]: *** [Modules/ThirdParty/TIFF/src/itktiff/tif_fax3sm.c] Error 126
make[4]: *** [Modules/ThirdParty/TIFF/src/itktiff/CMakeFiles/itktiff.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 38%] Built target itkhdf5
[ 51%] Built target itkvnl
[ 67%] Built target itkv3p_netlib
make[3]: *** [all] Error 2
make[2]: *** [ITK-prefix/src/ITK-stamp/ITK-install] Error 2
make[1]: *** [CMakeFiles/ITK.dir/all] Error 2
make: *** [all] Error 2

I've googled around already, but I do not a have a glue what to change.
I would appreciate any help.

Thanks in advance!
