### ISSUE TITLE
JAVA example

### ISSUE THREAD

**Issue by alexkarargyris** [kaspermarstal/SimpleElastix#24]
I am new to SimpleElastix and I was wondering if there is a simple JAVA example that uses SimpleElastix. Thanks

**Comment by kaspermarstal** [comment]
There is a small example [here](https://github.com/kaspermarstal/SimpleElastix/blob/SimpleElastix/Examples/SimpleElastix/SimpleElastix.java). Is there anything you're after in particular?

**Comment by kaspermarstal** [comment]
Hi Alex, was the example useful? FYI, in case you are working on a Mac, there is an issue with the SimpleITK Java build as mentioned in #25 which will be fixed in the next release. A workaround is referenced in that issue.

**Comment by alexkarargyris** [comment]
@kaspermarstal Thanks for the great information! I have not been able to install it to my project (Cmake issues). I have a couple of question since I am kind of new:
1) In the [JAVA example](https://github.com/kaspermarstal/SimpleElastix/blob/SimpleElastix/Examples/SimpleElastix/SimpleElastix.java) how can I get the registration transformation back? I want to apply the transformation on a mask.
2) What registration methods can I use with SimpleElastix? 

Thanks!

By the way I am running Windows so I should not have issues.

**Comment by kaspermarstal** [comment]
Np! 

You can warp a mask with the transformix class. Bear in mind I have not run the following code but it looks something like this:

```java
org.itk.simple.ImageFileReader reader = new org.itk.simple.ImageFileReader();
reader.setFileName("movingMask.nii");

org.itk.simple.SimpleTransformix transformix = new org.itk.simple.SimpleTransformix();
transformix.setInputImage(reader.execute());
transformix.setTransformParameterMap(elastix.getTransformParameterMap());

org.itk.simple.Image resultMask = transformix.execute()
```

As for the kinds of registration methods supported, many of the most common intensity-based registration methods are included. For metrics you have mean squares, normalized correlation, several versions of mutual information, variance over last dimension and a couple of regularization terms such as shape bending energy penalty, rigidity, mass-preserving penalty. These can be combined so you run multiple metrics in the same registration (e.g. mutual information and bending energy penalty). For transforms you have translation, rigid, affine, bspline and thin plate spline and for optimizers you have several quasi-newton methods and several gradient descent methods. However, most people (myself included) generally use the adaptive stochastich gradient descent optimization method. There are also several strategies for interpolation, sampling and multi-resolution schemes. The methods are explained in more detail in the [SimpleElastix documentation](http://simpleelastix.readthedocs.org/Introduction.html#registration-components) and in the [elastix manual](http://elastix.isi.uu.nl/download/elastix_manual_v4.8.pdf). There are no diffeomorphic log-demons or SyN methods etc.

If it all seems a bit daunting, you can use the preconfigured registration method that uses conservative parameters that work well in many cases. To use this method, simply omit passing a parameter map. You can use this as a starting point for configuring the registration procedure for your application. You can see the preconfigured parameters like this:

```java
org.itk.simple.SimpleElastix elastix = org.itk.simple.SimpleElastix();
org.itk.simple.PrettyPrint(elastix.GetParameterMap());
```

Hope this helps.

**Comment by alexkarargyris** [comment]
@kaspermarstal Great help and explanation! I am also probably troubling you with building errors I get on [windows](https://github.com/kaspermarstal/SimpleElastix/issues/26) and [mac](https://github.com/kaspermarstal/SimpleElastix/issues/27). Unfortunately I haven't been able to build the java wrapper to start working with SimpleElastix.

**Comment by kaspermarstal** [comment]
This is a known problem with the SimpleITK Java build. I have submitted a patch to SimpleITK which is included in the next SimpleITK release, after which it will be merged back into SimpleElastix.

**Comment by kaspermarstal** [comment]
Patch has now been merged into SimpleElastix.

**Comment by allenlu23** [comment]
Is there an easy way to extract the displacement field (i.e. same dimensions as the images but for multiple directions) out of the registration results? Say out of a B-Spline-based non-rigid registration?
