### ISSUE TITLE
Build error on El Capitan

### ISSUE THREAD

**Issue by alexkarargyris** [kaspermarstal/SimpleElastix#27]
I am following the instructions for compiling SimpleElastix on Mac but I am running on the following error while running `make -j4` : 

`
-- Installing: /Users/alexandroskarargyris/Downloads/build/ITK-prefix/include/ITK-4.8/itkVideoFileWriter.hxx
-- Installing: /Users/alexandroskarargyris/Downloads/build/ITK-prefix/include/ITK-4.8/itkVideoIOBase.h
-- Installing: /Users/alexandroskarargyris/Downloads/build/ITK-prefix/include/ITK-4.8/itkVideoIOFactory.h
-- Installing: /Users/alexandroskarargyris/Downloads/build/ITK-prefix/include/ITK-4.8/ITKVideoIOExport.h
-- Installing: /Users/alexandroskarargyris/Downloads/build/ITK-prefix/lib/cmake/ITK-4.8/Modules/ITKVideoIO.cmake
-- Installing: /Users/alexandroskarargyris/Downloads/build/ITK-prefix/lib/libITKVideoIO-4.8.a
[ 28%] Completed 'ITK'
[ 28%] Built target ITK
make: *** [all] Error 2
`

I also run cmake with options described in the [troubleshoot](http://simpleelastix.readthedocs.org/GettingStarted.html#pcre-perl-compatible-regular-expression-build-fails-on-mac-os-x) . Same error. Any help would be very much appreciated. I am interested in the java wrapper. So if someone has it for el capitan and wants to share it I am more than happy :)

**Comment by kaspermarstal** [comment]
What is your email? Or can you drop me a note at kaspermarstal@gmail.com?
