### ISSUE TITLE
How do I set the parameters in ParameterMap?

### ISSUE THREAD

**Issue by mongoose54** [kaspermarstal/SimpleElastix#29]
I am using the example and I am getting the following output:

`Running elastix with parameter map 0
Current time: Fri Mar 25 09:48:58 2016.
Installing all components.
InstallingComponents was successful.

ERROR:
  FixedImageType:  2D unsigned char
  MovingImageType: 2D unsigned char
  elastix was not compiled with this combination of ImageTypes!
  You have two options to solve this:
  1. Add the combination to the CMake parameters ELASTIX_IMAGE_nD_PIXELTYPES and ELASTIX_IMAGE_DIMENSIONS, re-cmake and re-compile.
  2. Change the parameters FixedInternalImagePixelType and/or MovingInternalImagePixelType in the elastix parameter file.

ERROR:
Something went wrong in the ComponentDatabase
Errors occurred!`

I am getting this with all the images it opens. Do I need to set FixedInternalImagePixelType and MovingInternalImagePixelType to float or something to work right? If yes how can I set this in Java? 
Or is my compilation wrong?

**Comment by kaspermarstal** [comment]
I suggest not fiddling with internal pixeltypes and instead do one of two things.

1. Go into the SimpleElastixBuildDirectory/elastix-build and set the USE_ALL_PXELTYPES CMake variable to ON and recompile the project. You may have to start the compilation from the SimpleElastixBuildDirectory/SimpleITK-build directory for the linker to pickup the updated libraries.
2. Cast the images to a float pixel type using the `CastImageFilter`: 
```java
    CastImageFilter caster = new CastImageFilter();
    caster.setOutputPixelType( sitkFloat32 );
    Image castImage = caster.execute( image );
```

Let me know how it goes!

**Comment by mongoose54** [comment]
@kaspermarstal Your second solution seems to work. Only for float32. Any other encoding seems to fail. Here is my code in case someone wants to use it:

`public void simpleelastixtest() {

		CastImageFilter caster = new CastImageFilter();
		caster.setOutputPixelType(PixelIDValueEnum.sitkFloat32);

		org.apache.logging.log4j.Logger log = MSLog4J2.getLogger();

		// Instantiate SimpleElastix
		org.itk.simple.SimpleElastix elastix = new org.itk.simple.SimpleElastix();

		// Read input
		org.itk.simple.ImageFileReader reader1 = new org.itk.simple.ImageFileReader();
		
		reader1.setFileName("brain1.png");
		Image castImage1 = caster.execute(reader1.execute());
		elastix.setFixedImage(castImage1);
		log.info(castImage1.getHeight());
		
		org.itk.simple.ImageFileReader reader2 = new org.itk.simple.ImageFileReader();
		reader2.setFileName("brain1.png");
		Image castImage2 = caster.execute(reader2.execute());
		elastix.setMovingImage(castImage2);
		log.info(castImage2.getHeight());
 
		elastix.setParameterMap(elastix.getDefaultParameterMap("rigid"));
		elastix.logToConsoleOn();


		// Perform registration
		elastix.execute();

		// Write result image
		ImageFileWriter writer = new org.itk.simple.ImageFileWriter();
		writer.setFileName("test.png");
		writer.execute(elastix.getResultImage());

		elastix.prettyPrint(elastix.getTransformParameterMap());

}`

However the example doesn't save the output image. Or more accurately Elastix is missing the [output path ](https://gist.github.com/mongoose54/69d00cc30b6002efc6cc#file-gistfile1-txt-L16) . Is there a way to set the output path for Elastix? Here is the [output ](https://gist.github.com/mongoose54/69d00cc30b6002efc6cc#file-gistfile1-txt) of the console. "Brain1.png" is this [image](http://simpleelastix.readthedocs.org/_images/BrainProtonDensity.png).

**Comment by kaspermarstal** [comment]
Looks like there is an error in the example. The call to `execute` on the writer should be `writer.execute(elastix.getResultImage(), "path/to/folder")`. Does this help?

The output path controls the directory of the log file. You can set the directory using `LogToFolder("path/to/folder").

**Comment by mongoose54** [comment]
@kaspermarstal Thanks for the suggestion. LogToFolder () helps with not producing errors. Now the logs are stored. However even with this the result image is written into the local path "test.png" with 0 size. I am attaching the new code:

`public void simpleelastixtest() {

    CastImageFilter caster = new CastImageFilter();
    caster.setOutputPixelType(PixelIDValueEnum.sitkFloat32);

    org.apache.logging.log4j.Logger log = MSLog4J2.getLogger();

    // Instantiate SimpleElastix
    org.itk.simple.SimpleElastix elastix = new org.itk.simple.SimpleElastix();

    // Read input
    org.itk.simple.ImageFileReader reader1 = new org.itk.simple.ImageFileReader();

    reader1.setFileName("brain1.png");
    Image castImage1 = caster.execute(reader1.execute());
    elastix.setFixedImage(castImage1);
    log.info(castImage1.getHeight());

    org.itk.simple.ImageFileReader reader2 = new org.itk.simple.ImageFileReader();
    reader2.setFileName("brain1.png");
    Image castImage2 = caster.execute(reader2.execute());
    elastix.setMovingImage(castImage2);
    log.info(castImage2.getHeight());

    elastix.setParameterMap(elastix.getDefaultParameterMap("rigid"));
    elastix.logToConsoleOn();
    elastix.logToFolder("\\elastixtestlogs\\");

    // Perform registration
    elastix.execute();

    // Write result image
    ImageFileWriter writer = new org.itk.simple.ImageFileWriter();
    writer.execute(elastix.getResultImage(),"test.png",false);

}`

Running elastix.getResultImage().getHeight() gives me the dimension of the image. So I guess the image is produced.

**Comment by mongoose54** [comment]
OK so I just figured it out why it didn't save the image. ImageFileWriter can export only to .nii file formats.
