### ISSUE TITLE
ImageFileReader and inputting data

### ISSUE THREAD

**Issue by mongoose54** [kaspermarstal/SimpleElastix#31]
Is there a way to read image data other than reading from the hard disk?

I see that this is the way to read an image:

>  org.itk.simple.ImageFileReader reader = new org.itk.simple.ImageFileReader();
>  reader.setFileName("image.png");

But I want to read from some buffer. Is it possible?

**Comment by kaspermarstal** [comment]
The [SimpleITK image class](http://www.itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1Image.html) exposes access to its raw buffer which you read from and write to. I am not aware if this is possible from wrapped languages but it is worth a try. Remember that the size of the buffer is the number of components*Xsize*Ysize and then Zsize of a 3D image. The buffer should be accessed as a 1-D array. More information is available via the link.

**Comment by kaspermarstal** [comment]
Closing issue. Feel free to reopen if you have further questions.
