### ISSUE TITLE
failed to run Hello code

### ISSUE THREAD

**Issue by vinllen** [kaspermarstal/SimpleElastix#32]
Hi, i run the code in this [post](http://simpleelastix.readthedocs.org/HelloWorld.html):
```
import SimpleITK as sitk
resultImage = sitk.Elastix(sitk.ReadImage("fixed.png"), sitk.ReadImage("moving.png"), "translation")
```
where the fixed.png and moving.png are just saved from the same page of fixedImage.nii and movingImage.nii, but the error shows below:
```
Traceback (most recent call last):
  File "test0.py", line 3, in <module>
    resultImage = sitk.Elastix(sitk.ReadImage("fixed.png"), sitk.ReadImage("moving.png"), "translation")
  File "/usr/local/lib/python2.7/site-packages/SimpleITK-0.9.1.dev26-py2.7-macosx-10.10-x86_64.egg/SimpleITK/SimpleITK.py", line 8950, in Elastix
    return _SimpleITK.Elastix(*args)
RuntimeError: Exception thrown in SimpleITK Elastix: /Users/vinllen/opt/simple_elastix/SimpleElastix/Code/Elastix/src/sitkSimpleElastix.hxx:90:
sitk::ERROR: Errors occured during registration. If you do not see any error message, set LogToConsoleOn() or LogToFolder("path/to/folder") to view elastix output.
```
I think it's the problem of PNG image, so i test the code in this [post](http://simpleelastix.readthedocs.org/AffineRegistration.html) with my own data of __nii__ formate:
```
import SimpleITK as sitk

elastix = sitk.SimpleElastix()
elastix.SetFixedImage(sitk.ReadImage("inia19-t1.nii"))
elastix.SetMovingImage(sitk.ReadImage("inia19-t1-brain.nii"))

plist = sitk.ParameterMapList()
plist.append(sitk.GetDefaultParameterMap("affine"))
plist.append(sitk.GetDefaultParameterMap("nonrigid"))
elastix.SetParameterMap(plist)

elastix.Execute()
sitk.WriteImage(elastix.GetResultImage())
```
It also cannot work:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    sitk.WriteImage(elastix.GetResultImage())
  File "/usr/local/lib/python2.7/site-packages/SimpleITK-0.9.1.dev26-py2.7-macosx-10.10-x86_64.egg/SimpleITK/SimpleITK.py", line 7469, in WriteImage
    return _SimpleITK.WriteImage(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'WriteImage'.
  Possible C/C++ prototypes are:
    itk::simple::WriteImage(itk::simple::Image const &,std::string const &,bool)
    itk::simple::WriteImage(itk::simple::Image const &,std::vector< std::string,std::allocator< std::string > > const &,bool)
```
Do you have any example datas that i can download to test your example code just like fixedImage.nii and movingImage.nii in the [post](http://simpleelastix.readthedocs.org/HelloWorld.html)? Thankyou verymuch.

**Comment by vinllen** [comment]
I kown how to write the image, but how to show the __.nii__ image in the command line. e.g., 
```
import SimpleITK as sitk
fixed = "sub01.nii"
moving = "sub02.nii"

fixedImage = sitk.ReadImage(fixed)
movingImage = sitk.ReadImage(moving)
sitk.ShowImage(fixed) #just like this
```

**Comment by PertuyF** [comment]
Hi Vinllen,
What you can do is display your image using matplotlib.imshow(). To do that you have to convert it to a numpy array, which is pretty simple with sitk.

`
import matplotlib.pyplot as plt
import SimpleITK as sitk

array = sitk.GetArrayFromImage(your_sitkImage)
plt.imshow(array)  # optionnal: you can use the keyword argument cmap to chang the LUT, I generally use cmap="gray"
`

There is also a sitk.Show() method, but it writes image to disk and open it externally (default used program is ImageJ) which can be slow, so I prefer the first approach. Anyway, read [this](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/) for more information, and particullarily part 01 and 10 for informations about how to display images.

**Comment by vinllen** [comment]
That's great, thanks a lot!

**Comment by kaspermarstal** [comment]
Closing issue. Feel free to reopen if the issue was not resolved.
