### ISSUE TITLE
Ubuntu 15.10 build failed with "error: ‘ProcessObject’ has not been declared"

### ISSUE THREAD

**Issue by izpr37** [kaspermarstal/SimpleElastix#37]
I am trying to build on a Dell Latitude E6500 laptop running Ubuntu 15.10. When trying invoking cmake/make the way described on **http://simpleelastix.readthedocs.io/GettingStarted.html** and in **https://github.com/kaspermarstal/SimpleElastix/issues/16**, I get the same error:

> build/elastix/src/Core/Main/elxElastixFilter.h: In member function ‘virtual void elastix::ElastixFilter<TFixedImage, TMovingImage>::SetParameterObject(const elastix::ParameterObject*)’:
/home/ilya/PR/SE/build/ITK-prefix/include/ITK-4.8/itkMacro.h:708:61: error: ‘ProcessObject’ has not been declared
     if ( _arg != itkDynamicCastInDebugMode< type * >( this->ProcessObject::GetInput(#name) ) )  \
                                                             ^
/home/ilya/PR/SE/build/elastix/src/Core/Main/elxElastixFilter.h:121:3: note: in expansion of macro ‘itkSetInputMacro’
   itkSetInputMacro( ParameterObject, ParameterObject );
   ^
/home/ilya/PR/SE/build/ITK-prefix/include/ITK-4.8/itkMacro.h:710:13: error: ‘ProcessObject’ has not been declared
       this->ProcessObject::SetInput( #name, const_cast< type * >( _arg ) );       \
             ^
/home/ilya/PR/SE/build/elastix/src/Core/Main/elxElastixFilter.h:121:3: note: in expansion of macro ‘itkSetInputMacro’
   itkSetInputMacro( ParameterObject, ParameterObject );
   ^
Code/Elastix/src/CMakeFiles/SimpleElastix.dir/build.make:54: recipe for target 'Code/Elastix/src/CMakeFiles/SimpleElastix.dir/sitkSimpleElastix.cxx.o' failed
make[5]: *** [Code/Elastix/src/CMakeFiles/SimpleElastix.dir/sitkSimpleElastix.cxx.o] Error 1
CMakeFiles/Makefile2:1276: recipe for target 'Code/Elastix/src/CMakeFiles/SimpleElastix.dir/all' failed
make[4]: *** [Code/Elastix/src/CMakeFiles/SimpleElastix.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/SimpleITK.dir/build.make:113: recipe for target 'SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build' failed
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
CMakeFiles/Makefile2:132: recipe for target 'CMakeFiles/SimpleITK.dir/all' failed
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
Makefile:75: recipe for target 'all' failed

**Comment by kaspermarstal** [comment]
Hi izpr37, this should be fixed as of 0ea3b748279e240a21f47b03d6f61ff85be52191. Can you do a `git pull` and check if you are compiling the latest version?
