### ISSUE TITLE
Error while building SimpleElastix

### ISSUE THREAD

**Issue by Plumax** [kaspermarstal/SimpleElastix#38]
Hi!

I'm trying to build SimpleElastix on a Linux Mint 17.3. However, while ITK and elastix seem to build without any problems, the building of SimpleElastix didn't work. I got in the end plenty of warning and 2 errors:

_/home/pgreillier/SimpleElastix/Code/Elastix/src/sitkSimpleTransformix.cxx: In constructor ‘itk::simple::SimpleTransformix::SimpleTransformix()’:
/home/pgreillier/SimpleElastix/Code/Elastix/src/sitkSimpleTransformix.cxx:34:9: error: ‘class itk::simple::SimpleTransformix’ has no member named ‘m_SetOutputDirectory’
   this->m_SetOutputDirectory = "";
         ^
/home/pgreillier/SimpleElastix/Code/Elastix/src/sitkSimpleTransformix.cxx:35:9: error: ‘class itk::simple::SimpleTransformix’ has no member named ‘m_SetLogFileName’
   this->m_SetLogFileName = "";_

Well, I put all the problematic output in an attached file.

Thanks!

[error_building_SE.txt](https://github.com/kaspermarstal/SimpleElastix/files/282227/error_building_SE.txt)

**Comment by kaspermarstal** [comment]
Hi Plumax, thanks for error report, it has now been fixed. Do a git pull and compile again. Let me know how it goes!

**Comment by Plumax** [comment]
Thank you for that!

But, now a problem appears in the end of the building...

In

>  file included from /home/pgreillier/SimpleElastix/Testing/Unit/SimpleITKTestHarness.h:45:0,
>                  from /home/pgreillier/SimpleElastix/Testing/Unit/sitkSimpleElastixTests.cxx:1:
> /home/pgreillier/SimpleElastix/Testing/Unit/sitkSimpleElastixTests.cxx:139:81: error: call of overloaded ‘Elastix(itk::simple::Image&, itk::simple::Image&, const char [12], bool, bool)’ is ambiguous
>    EXPECT_NO_THROW( Elastix( fixedImage, movingImage, "translation", true, false ) );
> 
> /home/pgreillier/SimpleElastix/Testing/Unit/sitkSimpleElastixTests.cxx: In member function ‘virtual void itk::simple::SimpleElastix_RegistrationWithPointSets_Test::TestBody()’:
> /home/pgreillier/SimpleElastix/Testing/Unit/sitkSimpleElastixTests.cxx:305:49: error: no matching function for call to ‘std::basic_ofstream<char>::open(std::string&)’
>    fixedPointSetFile.open( fixedPointSetFileName );
> 
> 
> /usr/include/c++/4.8/fstream:713:7: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char*’
> /home/pgreillier/SimpleElastix/Testing/Unit/sitkSimpleElastixTests.cxx:313:51: error: no matching function for call to ‘std::basic_ofstream<char>::open(std::string&)’
>    movingPointSetFile.open( movingPointSetFileName );

[error_building_SE_2.txt](https://github.com/kaspermarstal/SimpleElastix/files/284479/error_building_SE_2.txt)

**Comment by kaspermarstal** [comment]
Thanks for the feedback! Again, git pull and rebuild. The issue should now have been resolved.

**Comment by Plumax** [comment]
The compilation ended without error (seems so) and I can install the module in my python env.

But the ctest of my SimpleITK build failed for some program. 

Moreover, some functions seem to disappear like :

> sitk.ParameterMapList()

(Well that's the only one I finded for now)

[LastTestsFailed.txt](https://github.com/kaspermarstal/SimpleElastix/files/289000/LastTestsFailed.txt)
[LastTest.txt](https://github.com/kaspermarstal/SimpleElastix/files/289001/LastTest.txt)
[CTestCostData.txt](https://github.com/kaspermarstal/SimpleElastix/files/289002/CTestCostData.txt)

**Comment by kaspermarstal** [comment]
Thank your for your report! The tests has now been fixed and ParameterMapList() reinstated. Do a git pull and rerun the test suite, and let me know if you still see failures.

**Comment by kaspermarstal** [comment]
Hi, ParameterMapList was removed again, I apologize for any inconvenience, and owe you an explanation. In the latest release ParameterMapList was renamed to VectorOfParameterMap in order to align with the SimpleITK naming scheme e.g. VectorOfImage and making the API more friendly to existing SimpleITK users. I thought the two names could live side by side but this is not the case. Going forward, use VectorOfParameterMap where you have previously used ParameterMapList

Git pull and rebuild if complation of the Python module fails.
