### ISSUE TITLE
import SimpleITK error

### ISSUE THREAD

**Issue by stephenholtz** [kaspermarstal/SimpleElastix#39]
I am getting the following error when I try to use SimpleITK as explained in the documentation:

```
>>> import SimpleITK

Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```

Running it on OSX 10.11, using python 2.7.11 via anaconda. Didn't notice any problems during the build.

**Comment by kaspermarstal** [comment]
Hi Stephen, @gattia has previously found a solution to problem. Take a look at [this issue](https://github.com/kaspermarstal/SimpleElastix/issues/9) where he documented his findings. Try out his suggestions and let me know how goes!

**Comment by stephenholtz** [comment]
Apologies for missing that, it worked perfectly. Thanks!

To be clear I used the otool command to figure out where the dylib was and then used the line from the other issue:

> sudo install_name_tool -change "location it thinks the dylib is in" "location the dylib was actually in" "path to the _SimpleITK.so"

**Comment by kaspermarstal** [comment]
No problem, glad it works for you now.

**Comment by lgpang** [comment]
pip uninstall simpleitk
conda install -c simpleitk simpleitk=0.10.0

**Comment by fepegar** [comment]
I solved this using a modified version of @lgpang's solution:
```
conda uninstall simpleitk
sudo /usr/local/bin/pip uninstall simpleitk
conda install -c https://conda.anaconda.org/simpleitk SimpleITK
```

**Comment by kaspermarstal** [comment]
Note that this installs the official version of SimpleITK and not SimpleElastix.
