### ISSUE TITLE
SimpleElastiX v4.8 OpenCL filters

### ISSUE THREAD

**Issue by PertuyF** [kaspermarstal/SimpleElastix#4]
Hi !

I wanted to test OpenCL resampling in SimpleElastix but these flags are not activated by defaut in Cmake.
If I activate the following flags in Cmake (SimpleElastixDevelop branch):
ELASTIX_USE_OPENCL
USE_OpenCLFixedGenericPyramid
USE_OpenCLMovingGenericPyramid
USE_OpenCLResampler

I got these flags activated by default:
OPENCL_USE_NVIDIA_SDK ( which makes sense as I am using a nvidia GC and got the SDK installed from their drivers)
OPENCL_OPTIMIZATION_MAD_ENABLE

But when I build the project (Win7 using Visual Studio 2013) I get a "INTERNAL COMPILER error" on OpenCLFixedGenericPyramid.
And then some problems opening OpenCLFixedGenericPyramid.lib.

@kaspermarstal isn't it correct to use OpenCL filters yet with Selx ?

Fabien

**Comment by kaspermarstal** [comment]
Yes it should indeed be supported. Do you get the same error when compiling elastix stand-alone? Both as command line or library?

**Comment by PertuyF** [comment]
OK, I think I just messed up with a "." in my path...
I just renamed my build folder from ".../Elastix_selx_v4.8" to ".../Elastix_selx_v4-8" and the generation worked.
I am currently building SimpleElastix with this OpenCL enabled Elastix, I'll tell you if it's working or not.

**Comment by kaspermarstal** [comment]
OK great!

**Comment by PertuyF** [comment]
I had to rebuild the project.
It seems that LinearInterpolator and LinearResampleInterpolator were turned OFF in Cmake when I activated OpenCL. This led to errors in tests using SimpleElastix or SimpleTransformix.

Doing so I clarified a point about my previous bug, the "." may be in cause but  not activating the x64 compiler with "_IsNativeEnvironment=true" was also an issue.
Both elxOpenCLFixedGenericPyramid.cxx and elxOpenCLMovingGenericPyramid.cxx are currently generated and each process fills over 10GB memory at maximum.

I assume this could be a serious issue for many people...

The strange part is that before setting "_IsNativeEnvironment=true" I got a "not enought heap space" error instead of the standard "out of memory" error.

Do you know if it is a normal behaviour ?

**Comment by kaspermarstal** [comment]
I don't know why you see another error message but I can only assume that not enough heap space means the same thing as out of memory. 

10GB is a lot I'd give you that! Are you compiling in Release mode?

**Comment by PertuyF** [comment]
Yep, Release x64 for all.
The only thing I changed is the pixelTypes, I've set 2D, 3D and 4D to "unsigned char;char;unsigned short;short;float". That's the only thing I see that could play a role, but that much ?

By the way I got new strange errors compiling Selx (some Link error about "unresolve externals symbols"), so it's not working right now. I'll send you the log by email if you want to have a look.

**Comment by kaspermarstal** [comment]
Yes please do :grin: 

I would expect the number of pixel types to increase memory during the linking stage. Do you know if it is during build or link?

**Comment by PertuyF** [comment]
Sorry I can't tell if its during link or build.
I it can help I noticed for each process the memory goes up to 10GB quickly, then down to 500MB and raises again, but slowly, up to 1.5GB before the process ends.
Could it be related to a specific phase ?

**Comment by kaspermarstal** [comment]
My guess is it is related to the linking stages of language libraries. These are really big since they contain all the symbols (all filters with all pixel types) for the entire SimpleITK package plus the elastix symbols. Do you see the spike if you disable compiling all language wrappers?

**Comment by kaspermarstal** [comment]
Closing this issue. Feel free to reopen if needed.
