### ISSUE TITLE
2D VectorImage <unsigned char> not recognized

### ISSUE THREAD

**Issue by t-sanders** [kaspermarstal/SimpleElastix#42]
Kasper,
Trying to process `VectorImage <unsigned char, 2u>` (GetImageFromArray with RGB image as input)  gives the error

`SimpleElastix does not support the combination of 2-dimensional Unsupported pixel type.`

Can I compile SimpleElastix to include this type?

**Comment by kaspermarstal** [comment]
I am afraid not. Elastix does not support vector images. If you want to use SimpleElastix for this task you have to collapse the RGB channels to a single channel.
