### ISSUE TITLE
Error with SuperBuild on Linux Debian 8

### ISSUE THREAD

**Issue by pdecazes** [kaspermarstal/SimpleElastix#46]
Hi, 

I get this error when I try to build SimpleElastix :

--------------------------------------------------------------------------------

> In file included from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.h:147:0,
>                  from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkMeshFileReader.h:24,
>                  from /home/piedec/git/build/elastix/src/Common/itkMeshFileReaderBase.h:23,
>                  from /home/piedec/git/build/elastix/src/Common/itkTransformixInputPointFileReader.h:22,
>                  from /home/piedec/git/build/elastix/src/Core/ComponentBaseClasses/elxTransformBase.hxx:25,
>                  from /home/piedec/git/build/elastix/src/Core/ComponentBaseClasses/elxTransformBase.h:354,
>                  from /home/piedec/git/build/elastix/src/Core/Kernel/elxElastixTemplate.h:39,
>                  from /home/piedec/git/build/elastix/src/Core/Install/elxIncludes.h:39,
>                  from /home/piedec/git/build/elastix/src/Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.h:21,
>                  from /home/piedec/git/build/elastix/src/Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.cxx:19:
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx: In member function ‘bool itk::HexahedronCell<TCellInterface>::EvaluatePosition(itk::HexahedronCell<TCellInterface>::CoordRepType*, itk::HexahedronCell<TCellInterface>::PointsContainer*, itk::HexahedronCell<TCellInterface>::CoordRepType*, itk::HexahedronCell<TCellInterface>::CoordRepType*, double*, itk::HexahedronCell<TCellInterface>::InterpolationWeightType*) [with TCellInterface = itk::CellInterface<float, itk::CellTraitsInfo<4, double, float, long unsigned int, long unsigned int, long unsigned int, itk::Point<double, 4u>, itk::VectorContainer<long unsigned int, itk::Point<double, 4u> >, std::set<long unsigned int> > >; itk::HexahedronCell<TCellInterface>::CoordRepType = double; itk::HexahedronCell<TCellInterface>::PointsContainer = itk::VectorContainer<long unsigned int, itk::Point<double, 4u> >; itk::HexahedronCell<TCellInterface>::InterpolationWeightType = float]’:
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx:380:9: warning: iteration 3u invokes undefined behavior [-Waggressive-loop-optimizations]
>          tcol[j] += pt[j] * derivs[i + 16];
>          ^
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx:375:7: note: containing loop
>        for ( unsigned int j = 0; j < PointDimension; j++ )
>        ^
> In file included from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.h:147:0,
>                  from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkMeshFileReIn file included from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.h:147:0,
>                  from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkMeshFileReader.h:24,
>                  from /home/piedec/git/build/elastix/src/Common/itkMeshFileReaderBase.h:23,
>                  from /home/piedec/git/build/elastix/src/Common/itkTransformixInputPointFileReader.h:22,
>                  from /home/piedec/git/build/elastix/src/Core/ComponentBaseClasses/elxTransformBase.hxx:25,
>                  from /home/piedec/git/build/elastix/src/Core/ComponentBaseClasses/elxTransformBase.h:354,
>                  from /home/piedec/git/build/elastix/src/Core/Kernel/elxElastixTemplate.h:39,
>                  from /home/piedec/git/build/elastix/src/Core/Install/elxIncludes.h:39,
>                  from /home/piedec/git/build/elastix/src/Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.h:21,
>                  from /home/piedec/git/build/elastix/src/Components/Transforms/SplineKernelTransform/elxSplineKernelTransform.cxx:19:
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx: In member function ‘bool itk::HexahedronCell<TCellInterface>::EvaluatePosition(itk::HexahedronCell<TCellInterface>::CoordRepType*, itk::HexahedronCell<TCellInterface>::PointsContainer*, itk::HexahedronCell<TCellInterface>::CoordRepType*, itk::HexahedronCell<TCellInterface>::CoordRepType*, double*, itk::HexahedronCell<TCellInterface>::InterpolationWeightType*) [with TCellInterface = itk::CellInterface<float, itk::CellTraitsInfo<4, double, float, long unsigned int, long unsigned int, long unsigned int, itk::Point<double, 4u>, itk::VectorContainer<long unsigned int, itk::Point<double, 4u> >, std::set<long unsigned int> > >; itk::HexahedronCell<TCellInterface>::CoordRepType = double; itk::HexahedronCell<TCellInterface>::PointsContainer = itk::VectorContainer<long unsigned int, itk::Point<double, 4u> >; itk::HexahedronCell<TCellInterface>::InterpolationWeightType = float]’:
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx:380:9: warning: iteration 3u invokes undefined behavior [-Waggressive-loop-optimizations]
>          tcol[j] += pt[j] * derivs[i + 16];
>          ^
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx:375:7: note: containing loop
>        for ( unsigned int j = 0; j < PointDimension; j++ )
>        ^
> In file included from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.h:147:0,
>                  from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkMeshFileReader.h:24,
>                  from /home/piedec/git/build/elastix/src/Common/itkMeshFileReaderBase.h:23,
>                  from /home/piedec/git/build/elastix/src/Common/itkTransformixInputPointFileReader.h:22,
>                  from /home/piedec/git/build/elastix/src/Core/ComponentBaseClasses/elxTransformBase.hxx:25,
>                  from /home/piedec/git/build/elastix/src/Core/ComponentBaseClasses/elxTransformBase.h:354,
>                  from /home/piedec/git/build/elastix/src/Core/Kernel/elxElastixTemplate.h:39,
>                  from /home/piedec/git/build/elastix/src/Core/Install/elxIncludes.h:39,
>                  from /home/piedec/git/build/elastix/src/Components/Transforms/TranslationTransform/elxTranslationTransform.h:21,
>                  from /home/piedec/git/build/elastix/src/Components/Transforms/TranslationTransform/elxTranslationTransform.cxx:19:
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx: In member function ‘bool itk::HexahedronCell<TCellInterface>::EvaluatePosition(itk::HexahedronCell<TCellInterface>::CoordRepType*, itk::HexahedronCell<TCellInterface>::PointsContainer*, itk::HexahedronCell<TCellInterface>::CoordRepType*, itk::HexahedronCell<TCellInterface>::CoordRepType*, double*, itk::HexahedronCell<TCellInterface>::InterpolationWeightType*) [with TCellInterface = itk::CellInterface<float, itk::CellTraitsInfo<4, double, float, long unsigned int, long unsigned int, long unsigned int, itk::Point<double, 4u>, itk::VectorContainer<long unsigned int, itk::Point<double, 4u> >, std::set<long unsigned int> > >; itk::HexahedronCell<TCellInterface>::CoordRepType = double; itk::HexahedronCell<TCellInterface>::PointsContainer = itk::VectorContainer<long unsigned int, itk::Point<double, 4u> >; itk::HexahedronCell<TCellInterface>::InterpolationWeightType = float]’:
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx:380:9: warning: iteration 3u invokes undefined behavior [-Waggressive-loop-optimizations]
>          tcol[j] += pt[j] * derivs[i + 16];
>          ^
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx:375:7: note: containing loop
>        for ( unsigned int j = 0; j < PointDimension; j++ )
>        ^
> In file included from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.h:147:0,
>                  from /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkMeshFileReader.h:24,
>                  from /home/piedec/git/build/elastix/src/Common/itkMeshFileReaderBase.h:23,
>                  from /home/piedec/git/build/elastix/src/Common/itkTransformixInputPointFileReader.h:22,
>                  from /home/piedec/git/build/elastix/src/Core/ComponentBaseClasses/elxTransformBase.hxx:25,
>                  from /home/piedec/git/build/elastix/src/Core/ComponentBaseClasses/elxTransformBase.h:354,
>                  from /home/piedec/git/build/elastix/src/Core/Kernel/elxElastixTemplate.h:39,
>                  from /home/piedec/git/build/elastix/src/Core/Install/elxIncludes.h:39,
>                  from /home/piedec/git/build/elastix/src/Components/Transforms/StackTransform/elxBSplineStackTransform.h:21,
>                  from /home/piedec/git/build/elastix/src/Components/Transforms/StackTransform/elxBSplineStackTransform.cxx:18:
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx: In member function ‘bool itk::HexahedronCell<TCellInterface>::EvaluatePosition(itk::HexahedronCell<TCellInterface>::CoordRepType*, itk::HexahedronCell<TCellInterface>::PointsContainer*, itk::HexahedronCell<TCellInterface>::CoordRepType*, itk::HexahedronCell<TCellInterface>::CoordRepType*, double*, itk::HexahedronCell<TCellInterface>::InterpolationWeightType*) [with TCellInterface = itk::CellInterface<float, itk::CellTraitsInfo<4, double, float, long unsigned int, long unsigned int, long unsigned int, itk::Point<double, 4u>, itk::VectorContainer<long unsigned int, itk::Point<double, 4u> >, std::set<long unsigned int> > >; itk::HexahedronCell<TCellInterface>::CoordRepType = double; itk::HexahedronCell<TCellInterface>::PointsContainer = itk::VectorContainer<long unsigned int, itk::Point<double, 4u> >; itk::HexahedronCell<TCellInterface>::InterpolationWeightType = float]’:
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx:380:9: warning: iteration 3u invokes undefined behavior [-Waggressive-loop-optimizations]
>          tcol[j] += pt[j] * derivs[i + 16];
>          ^
> /home/piedec/git/build/ITK-prefix/include/ITK-4.8/itkHexahedronCell.hxx:375:7: note: containing loop
>        for ( unsigned int j = 0; j < PointDimension; j++ )
>        ^
> 

Do you know a solution ?

Thanks

**Comment by kaspermarstal** [comment]
Hi pdecazes, as far as I can see the output you posted concerns warnings, not errors. If your build is blocked by these warnings you should disable treating warnings as errors. 

The warnings come from deep inside ITK and is not something we can fix in SimpleElastix. I have seen these warnings many times but have yet to experience registration issues because of them. I would not worry about it.
