### ISSUE TITLE
Build error gcc 4.7.2

### ISSUE THREAD

**Issue by woutdenolf** [kaspermarstal/SimpleElastix#47]
I get the following errors when using the superbuild: [log.txt](https://github.com/kaspermarstal/SimpleElastix/files/399421/log.txt). It seems to be related to the use of template function ParameterObject::ToString in elxElastixFilter.hxx:

    parameterMapVector[ i ][ "FixedImageDimension" ] 
      = ParameterValueVectorType( 1, ParameterObject::ToString( FixedImageDimension ) );
    parameterMapVector[ i ][ "MovingImageDimension" ] 
      = ParameterValueVectorType( 1, ParameterObject::ToString( MovingImageDimension ) );

Both FixedImageDimension and MovingImageDimension don't seem to be defined anywhere so the compiler gives a "no matching function for call to elastix::ParameterObject::ToString" error as it can't derive the template type (at least I think that's the problem).

**Comment by gdhugo** [comment]
I'm having the same problem on Centos v6, running gcc 4.4.7.  It builds OK on a Mac, and I diff'ed the SimpleElastix/Code/Elastix/* files, along with the ITK and elastix code (cloned with git) in the build directory between linux/mac and these all matched exactly, so I suspect a configuration or compiler issue?

**Comment by kaspermarstal** [comment]
I am having a similar issue on my Mac. While the error message is slightly different it looks like it is the same issue. 
```
  "FixedImageDimension", referenced from:
      elastix::ElastixFilter<itk::Image<signed char, 2u> >::GenerateData() in libSimpleElastix-0.10.a(sitkSimpleElastix.cxx.o)
```
Are you guys on the master branch or the develop branch?

I have been trying to fix this problem quite some time now and will continue investigating. If you find any out anything interesting please let me know!

**Comment by kaspermarstal** [comment]
Hi, this issue is now fixed on the develop branch (on my machine at least). Can you compile now?

**Comment by gdhugo** [comment]
The develop branch compiled correctly on my linux machine. Thanks!

**Comment by kaspermarstal** [comment]
No problem, good to hear!
