### ISSUE TITLE
make error: RPC failed; result=22, HTTP code = 405 when cloning ITK in SuperBuild

### ISSUE THREAD

**Issue by gdhugo** [kaspermarstal/SimpleElastix#48]
When trying to build, I get the following error when trying to clone ITK using the SuperBuild:
RPC failed; result=22, HTTP code = 405

This is using git 1.7.1 on Centos 6.7.  

It appears the issue is similar to [this one](https://github.com/FlowForwarding/LINC-Switch/issues/271), since applying the workaround and changing 'http:' to 'https:' in SuperBuild/External_ITK.cmake appears to have fixed the issue (at least I can now clone/build ITK as part of the SuperBuild). I also see in the main SimpleITK repo that the clone command is structured as:

set(ITK_REPOSITORY "${git_protocol}://itk.org/ITK.git")

instead of 

set(ITK_REPOSITORY http://itk.org/ITK.git)

which may be a better long term solution?

Finally, this issue would appear to also be problematic in the clone call in External_elastix.cmake.

**Comment by kaspermarstal** [comment]
Thank you for pointing this out. It will be fixed in the next release!

**Comment by gdhugo** [comment]
The develop branch seems to have this problem fixed as it compiled correctly this morning.

**Comment by kaspermarstal** [comment]
Great! Thanks for the feedback. Closing issue. Feel free to open if anything goes wrong again.

**Comment by ctr26** [comment]
I'm having this same problem when installing elastix

**Comment by h1310321230** [comment]
I also get this mistake.
`
Cloning into 'ITK'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'ITK'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

`
