### ISSUE TITLE
WriteParameterFile introduces errors by representing ints as floats

### ISSUE THREAD

**Issue by JorritPosthuma** [kaspermarstal/SimpleElastix#5]
Hi!

I recently stumbled upon an error that transformix couldn't read the result from elastix. I used `WriteParameterFile` to save the intermediate result, which writes every number as a float. However, a large number (like NumberOfParameters: 1589952) is represented using exponents (1.58995e+0, which is 2 off), and can therefore introduce problems.

I fixed it temporarily by using my own method:
```python
def parameterMapToString(pmap):
    text = ''
    for key in pmap:
        text += '(' + key
        for value in pmap[key]:
            text += ' '
            try:
                text += str(int(value)) # First, try writing as an integer
            except ValueError:
                try:
                    text += str(float(value))
                except ValueError:
                    text += '"' + value + '"'
        text += ')\n'
    return text
```

**Comment by PertuyF** [comment]
Hi Jorrit,
I went trough a similar issue but I'm my case it was caused by an incorrect DefaultPixelValue, which was an empty character instead of a digit.

Does it work if you try:

T = selx.GetTransformParameterMap()
T["DefaultPixelValue"] = [0]

And then pass it to tfmx() ?

**Comment by JorritPosthuma** [comment]
I've looked at the old (/wrong) file and the DefaultPixelValue value seems to be ok 😊.

**Comment by kaspermarstal** [comment]
Does this fix your issue?

**Comment by JorritPosthuma** [comment]
Haha, just finished compiling the previous commit 😋. Will try!

**Comment by kaspermarstal** [comment]
I feel your pain :laughing:

:grimacing::gun:

**Comment by kaspermarstal** [comment]
Issue seems to fixed. Feel free to reopen if needed.
