### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by hilmzaditya** [kaspermarstal/SimpleElastix#51]
Hi,

I success to build ITK and Elastix but when I build simple Elastix, I found the error. I am using Visual studio 2013, ITK v.4.8 and Elastix v.4.8.

Error   7   error C2660: 'itk::ProcessObject::SetInput' : function does not take 1 arguments    ...\src\Code\Elastix\include\sitkSimpleTransformix.hxx  21  1   SimpleTransformix

Error   8   error C2039: 'SetInputPointSetFileName' : is not a member of 'elastix::TransformixFilter<TMovingImage>' ...\src\Code\Elastix\include\sitkSimpleTransformix.hxx  24  1   SimpleTransformix.

Any thoughts or suggestions would be greatly appreciated.

Thanks,

Hilmi

**Comment by kaspermarstal** [comment]
Hi hilmzaditya, this is an old error, try to pull in the latest changes and let me know how it goes.
