### ISSUE TITLE
Passing Numpy Arrays to SimpleElastix.SetFixedImage()

### ISSUE THREAD

**Issue by pskeshu** [kaspermarstal/SimpleElastix#55]
Hi,

Is it possible to pass a numpy array instead of a file from the disk to SimpleElastix.SetFixedImage() and SimpleElastix.SetMovingImage()?

I have an image processing pipeline, which includes some background subtraction and cropping before I'm registering them, so passing an array would be more helpful than writing them to a file and passing it on to registration.

**Comment by PertuyF** [comment]
Hi pskeshu,

It is not possible to pass a ``numpy.array`` directly, but you can use a ``sitk.Image``.
So basically it is very simple to convert the former into the later:
```
import SimpleITK as sitk

selx = sitk.SimpleElastix()

selx.SetFixedImage(sitk.GetImageFromArray(yourNumpyArray))
selx.SetMovingImage(sitk.GetImageFromArray(yourOtherNumpyArray))
# Continue...
```

And you can do the conversion backward with the result of the registration:
```
# After registration...
yourResultAsNumpyArray = sitk.GetArrayFromImage(selx.GetResultImage())
```

Hope this helps.

**Comment by pskeshu** [comment]
That's exactly what I was looking for. Slightly unrelated, but I see that a lot of text files are being generated in my working directory. For example: IterationInfo.0.R0.txt and TransformParameters.0.txt. I'm not sure what exactly they are storing. I could always cleanup the files, but is this a normal behaviour?

**Comment by kaspermarstal** [comment]
Normal, yes, definitely but not desired! This will be fixed in the next release.
