### ISSUE TITLE
Elastix output in stdout buffer upon transforming with sitk.Transformix()

### ISSUE THREAD

**Issue by pskeshu** [kaspermarstal/SimpleElastix#56]
When I am wrapping a population of images using Transformix(), it prints the following output for each image:

```
ELASTIX version: 4.801
Command line options from ElastixBase:
-out      ./
-threads  unspecified, so all available threads are used
-def      unspecified, so no input points transformed
-jac      unspecified, so no det(dT/dx) computed
-jacmat   unspecified, so no dT/dx computed

Reading input image ...
  Reading input image took 0.000002 s
Calling all ReadFromFile()'s ...
  Calling all ReadFromFile()'s took 0.000045 s
Transforming points ...
  The command-line option "-def" is not used, so no points are transformed
  Transforming points done, it took 0.00s
Compute determinant of spatial Jacobian ...
  The command-line option "-jac" is not used, so no det(dT/dx) computed.
  Computing determinant of spatial Jacobian done, it took 0.00s
Compute spatial Jacobian (full matrix) ...
  The command-line option "-jacmat" is not used, so no dT/dx computed.
  Computing spatial Jacobian done, it took 0.00s
Resampling image and writing to disk ...
  Resampling took 0.19s
```
Is this a known issue? Is there any way to suppress this?

**Comment by PertuyF** [comment]
Hi pskeshu,

It is not an issue, it is the standard ElastiX/TransformiX verbose that output to the console.
If you don't want to see it you can set ``selx.LogToConsoleOff()`` or ``selx.SetLogToConsole(False)``.

**Comment by pskeshu** [comment]
SimpleTransformix.LogToConsoleOff() fixed it for me. Thanks!

**Comment by veritas9872** [comment]
@pskeshu @PertuyF Hello. I think it might be a good idea to mention that this is a method within each type of class, e.g. `transformixImageFIlter = sitk.TransformixImageFilter()`, `transformixImageFIlter .SetLogToConsole(False)`

**Comment by markbuckup** [comment]
Hi. I'm trying the above commands but my cell is still producing the output:

```
Time spent on saving the results, applying the final transform etc.: 44 ms.
ELASTIX version: 5.000
Command line options from ElastixBase:
-fMask    unspecified, so no fixed mask used
-mMask    unspecified, so no moving mask used
-out      ./
-threads  unspecified, so all available threads are used
WARNING: The parameter "UseDirectionCosines", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.

WARNING: The option "UseDirectionCosines" was not found in your parameter file.
  From elastix 4.8 it defaults to true!
This may change the behavior of your registrations considerably.

Command line options from TransformBase:
-t0       unspecified, so no initial transform used

Reading images...
```

This is my original code:

`#perform the registration           
            elastixImageFilter = sitk.ElastixImageFilter.SetLogToConsole(False)
            elastixImageFilter.SetFixedImage(sitk.GetImageFromArray(cropped_image_a))
            elastixImageFilter.SetMovingImage(sitk.GetImageFromArray(cropped_image_b))
            parameterMapVector = sitk.GetDefaultParameterMap('translation')
            parameterMapVector['MaximumNumberOfIterations'] = [str(iterations)]
            parameterMapVector['NumberOfResolutions'] = [str(resolutions)]
            parameterMapVector['NumberOfSpatialSamples'] = [str(spatial_samples)]
            elastixImageFilter.SetParameterMap(parameterMapVector)
            elastixImageFilter.Execute()`

Any guidance?
