### ISSUE TITLE
fatal error: 'SimpleITK.h' file not found

### ISSUE THREAD

**Issue by johnashcroft105** [kaspermarstal/SimpleElastix#62]
Hi all,

I'm running SimpleElastix on MacOSX 10.11.5

I'm trying to run the DicomSeriesReader.cxx example

#
% From terminal: 
g++ ~/SimpleElastix/src/Examples/DicomSeriesReader.cxx

% Returns:
/Users/xxxxx/SimpleElastix/src/Examples/DicomSeriesReader.cxx:21:10: fatal error: 'SimpleITK.h' file not found
#include <SimpleITK.h>
         ^
1 error generated.

#
% SimpleITK.h is located in:     /Users/xxxxx/SimpleElastix/build/include/SimpleITK-0.10/SimpleITK.h
% And it is in my path:

type -P SimpleITK.h
/Users/xxxxx/SimpleElastix/build/include/SimpleITK-0.10/SimpleITK.h

% which is set as follows:

echo $PATH
/Users/xxxxx/SimpleElastix/:/Users/xxxxx/SimpleElastix/build:/Users/xxxxx/SimpleElastix/src:/Users/xxxxx/SimpleElastix/src/Examples:/Users/xxxxx/SimpleElastix/build/include:/Applications/CMake.app/Contents/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

#
Has anyone had this problem before? Am I setting my path wrong? I added a bunch of subfolders explicitly because It doesn't seem to be able to find things otherwise. 

1. What is the best way to set my path for SimpleElastix?
2. How do I fix this problem with SimpleITK.h?

Thanks in advance

**Comment by kaspermarstal** [comment]
It looks like you are trying to compile the .cxx file manually? Can you elaborate on why you want to do this?

The documentation explains [how to compile SimpleElastix via the terminal](https://simpleelastix.readthedocs.io/GettingStarted.html#superbuild-on-linux):
```
$ git clone https://github.com/kaspermarstal/SimpleElastix
$ mkdir build
$ cd build
$ cmake ../SimpleElastix/SuperBuild
$ make -j4

**Comment by kaspermarstal** [comment]
Did this work for you?
