### ISSUE TITLE
Call to sitk.PrintParameterMap is empty

### ISSUE THREAD

**Issue by johnashcroft105** [kaspermarstal/SimpleElastix#63]
I don't seem to be able to retrieve the information in my parameter maps.

For example:

> import SimpleITK as sitk
> SimpleElastix = sitk.SimpleElastix()
> parameterMap = SimpleElastix.GetParameterMap( )
> sitk.PrintParameterMap(parameterMap)

and nothing comes up

> x=sitk.PrintParameterMap(parameterMap)
> print(x)

returns  None

> sitk.PrintParameterMap(sitk.GetDefaultParameterMap("translation"))

has the same behavior

It works fine otherwise. I can coregister images easily. Just can't see what is in the parameter map.

#
P.S. 
On that note. The documentation says to use the following code:

> import SimpleITK as sitk
 SimpleElastix = sitk.SimpleElastix() 
parameterMaps = SimpleElastaix.GetParameterMaps() 
 sitk.PrintParameterMaps(parameterMaps)

but SimpleITK.py only contains PrintParameterMap and GetParameterMap, without an "s"

**Comment by kaspermarstal** [comment]
Thank you for the bug report! A fix will be merged soon. In the meantime you can use the `PrintParameterMap()` method on the `SimpleElastix` object itself:

```
import SimpleITK as sitk
SimpleElastix = sitk.SimpleElastix()
SimpleElastix.PrintParameterMap()

**Comment by johnashcroft105** [comment]
Terrific! Thank you.
