### ISSUE TITLE
How to specify CMake path in SuperBuild script?

### ISSUE THREAD

**Issue by snapfinger** [kaspermarstal/SimpleElastix#64]
I tried using SuperBuild on Linux (CentOS 7), but it required at least CMake 3.0 while the version installed on the server I use is 2.8.  I don't have sudo access, so I'm not able to directly upgrade CMake. I downloaded higher version CMake binary and put it in a directory, but how to let SuperBuild use this CMake path to compile instead of using the original default one?

**Comment by kaspermarstal** [comment]
Just run your own CMake executable directly. For example, assuming you have put your CMake binary into `home/snapfinger/development/CMake/` and cloned SimpleElastix into `home/snapfinger/development/SimpleElastix/`:

```
$ /home/snapfinger/development/CMake/cmake ../../SimpleElastix/SuperBuild
```

Make sure it has permission to execute. You can do this with `$ chmod +x /home/snapfinger/development/CMake/cmake`.

**Comment by snapfinger** [comment]
It works! Thanks!

**Comment by kaspermarstal** [comment]
You are welcome :)
