### ISSUE TITLE
Problem linking to SimpleElastix in CMake C++ project

### ISSUE THREAD

**Issue by gdhugo** [kaspermarstal/SimpleElastix#65]
I'm having some issues constructing and building a small test C++ project using CMake, using SimpleElastix release 0.10.  I adapted the instructions for constructing a CMake project for SimpleITK, which basically comes down to:

1. constructing a CMakeLists.txt file such as:

```
project(TestCPP)

find_package(SimpleITK REQUIRED)
include(${SimpleITK_USE_FILE})

add_executable ( testcpp testcpp.cxx )
target_link_libraries ( testcpp ${SimpleITK_LIBRARIES} )
```

2. for a basic C++ file such as:

```
#include "SimpleITK.h"
#include <stdlib.h>

namespace sitk = itk::simple;

int main(int argc, char *argv[])
{
  sitk::Image image = sitk::Image(std::vector<unsigned int>(32,32), sitk::sitkVectorUInt8, 3);
  return 0;
}
```

3. When running CMake, setting the SimpleITK_DIR variable to '/pathToSuperBuild/lib/cmake/SimpleITK-0.10'.

When I do this, I receive the following error (this is on Mac OS X 10.11 but I receive a similar error on Centos 6):

```
[ 50%] Building CXX object CMakeFiles/testcpp.dir/testcpp.o
[100%] Linking CXX executable testcpp
ld: library not found for -lelastix
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [testcpp] Error 1
make[1]: *** [CMakeFiles/testcpp.dir/all] Error 2
make: *** [all] Error 2
```

Any help would be appreciated.

**Comment by kaspermarstal** [comment]
The project is unfortunately not as stand-alone yet as I would like. You have to include the `${ELASTIX_USE_FILE}` as well. The SuperBuild builds the Examples directory as an external project as a test for your exact use case. You can see the CMake commands required to do this in [Examples/CMakeLists.txt](https://github.com/kaspermarstal/SimpleElastix/blob/e9cfb336a84a489feb5a24efa3a4814f5e08b5b3/Examples/CMakeLists.txt#L13-L29). 

If anyone out there knows how to install an imported library any help is greatly appreciated.

**Comment by gdhugo** [comment]
Thanks, this worked.  I'm not an expert with CMake, but I'll see if I can help with the import issue.

**Comment by kaspermarstal** [comment]
Glad it worked. Great, let me know if you find a solution!

**Comment by kaspermarstal** [comment]
Feel free to open again
