### ISSUE TITLE
SVN Checkout error

### ISSUE THREAD

**Issue by TylerCork** [kaspermarstal/SimpleElastix#7]
While building the program I come across this error:

[ 16%] Built target PCRE
[ 32%] Built target ITK
[ 48%] Built target Swig
[ 51%] Performing download step (SVN checkout) for 'elastix'
svn: E170001: Unable to connect to a repository at URL 'https://svn.bigr.nl/elastix/trunkpublic'
svn: E170001: OPTIONS of 'https://svn.bigr.nl/elastix/trunkpublic': authorization failed: Could not authenticate to server: rejected Basic challenge (https://svn.bigr.nl)
make[2]: *** [elastix-prefix/src/elastix-stamp/elastix-download] Error 1
make[1]: *** [CMakeFiles/elastix.dir/all] Error 2
make: *** [all] Error 2

Does anybody have a solution to this problem yet?

**Comment by kaspermarstal** [comment]
Hi Tyler. Thanks for reporting the issue. It seems to be a common problem with git-svn. I have added a workaround to the docs which you can see [here](http://simpleelastix.readthedocs.org/GettingStarted.html#the-superbuild-throws-server-ssl-certificate-verification-failed-certificate-has-expired-during-checkout-of-elastix). Let me know if this fixes your problem!

**Comment by TylerCork** [comment]
Thank you for creating that work around. The work around allowed me to finish building the program!

**Comment by kaspermarstal** [comment]
NP!

**Comment by gattia** [comment]
Hi Kasper, I am also trying to install simpleElastix and have run into the same error. I looked at the docs and didn't see the workaround for this specific issue. I may be missing something obvious... . I am running Os X. Any suggestions

Thanks, 

Anthony.

**Comment by gattia** [comment]
I found the answer. 
For anyone else that might have this issue. The answer was in the commit and not the documents. 

Here it it: 
Solution 1: We run :code:`svn info https://svn.bigr.nl/elastix/trunkpublic/` in out terminal. It will then prompt us to "(R)eject, accept (t)emporarily or accept (p)ermanently?" the certificate. Hit 'p' and then enter. It may then ask us for our SVN username, which is :code:`elastixguest`, and password, which is also :code:`elastixguest`. Then we restart the build.

(https://github.com/kaspermarstal/SimpleElastix/commit/14f8bdc38cd0b485be7fa5de06ece4208f8c3ccb)

**Comment by kaspermarstal** [comment]
Hi gattia, thanks for the info, the docs are now updated properly.

**Comment by talmo** [comment]
FYI: The change in 8faed11 (SVN_TRUST_CERT 1) doesn't appear to fix this. I'm still getting the error below if I don't use the workaround above.
```
4>------ Build started: Project: elastix, Configuration: Release x64 ------
4>  Building Custom Rule C:/Toolbox/SimpleElastix/SuperBuild/CMakeLists.txt
4>  CMake does not need to re-run because C:\se\CMakeFiles\generate.stamp is up-to-date.
4>  Creating directories for 'elastix'
4>  Performing download step (SVN checkout) for 'elastix'
4>  svn: E170013: Unable to connect to a repository at URL 'https://svn.bigr.nl/elastix/trunkpublic'
4>  svn: E230001: Server SSL certificate verification failed: certificate has expired, issuer is not trusted
4>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
```
