### ISSUE TITLE
Stuck in the single line code

### ISSUE THREAD

**Issue by CPFLAME** [kaspermarstal/SimpleElastix#76]
Hi, I just run this code for image registration,
![yyw c_wxd2 i yn1 9pzr5l](https://cloud.githubusercontent.com/assets/13843079/23402901/9386b020-fde8-11e6-81ec-9ebe6b5c790a.png)
but It seems to run for a long time.
Any help?

**Comment by PertuyF** [comment]
You can try to display the log to the console, this way you'll see what's going on.
`sitk.LogToConsoleOn()`

Otherwise you can monitor your CPU usage, but logToConsole should do.

If the registration is going on, but is very slow, there will be things to investigate.
