### ISSUE TITLE
Python: simpleTransformix on a point set with an initial transformation

### ISSUE THREAD

**Issue by NHPatterson** [kaspermarstal/SimpleElastix#78]
I am doing a registration on two images and then applying the transform to a set of points. 
First, I do an affine registration, I have no problem using the transformationMap output in transformix.
```
selx.Execute()
Affine_transformationMap = selx.GetTransformParameterMap()
```

However, when I do a transformation where I take a previous transform from file (a saved transformationparameter from the previous affine transformation) :
```

selx.SetParameterMap(param)
selx.SetFixedImage(fixed)
selx.SetMovingImage(moving)
selx.SetInitialTransformParameterFileName('affine.txt')
selx.Execute()
nl_transformationMap = selx.GetTransformParameterMap()

```
I can then no longer use Transformix to apply the transformation if I pass the transform from within Python, it crashes. I have no problem applying the affine transformation by itself.

```
    transformix = sitk.SimpleTransformix()

    # Read Input
    transformix.SetFixedPointSetFileName('srcpts.txt')
    transformix.SetTransformParameterMap(nl_transformationMap)
    # Perform warp
    transformix.Execute()
```

It also works if I do a VectorOfParameterMap for the registration, where I pass the parameter files for the affine and non-linear registration sequentially. (the output appears to point to both transformations). However, I want to test non-linear parameters iteratively and repeating the affine transformation every single registration is unnecessarily time consuming.
Here is the Transformix log:

> ELASTIX version: 4.801
Command line options from ElastixBase:
-out      ./
-threads  unspecified, so all available threads are used
-def      points_tform\srcpts.txt
-jac      unspecified, so no det(dT/dx) computed
-jacmat   unspecified, so no dT/dx computed
Calling all ReadFromFile()'s ...

Any advice?

**Comment by kaspermarstal** [comment]
Mixing file-based parameter files with in-memory parameter files is unfortunately not supported. I suspect this is where your error occurs. Is it possible to perform affine registration, warp the image with the affine transform, and then perform all your b-spline registrations with this image? You will (admittedly) be resampling your moving image twice, but perhaps the gain in speed makes up for it.

**Comment by NHPatterson** [comment]
Yes, this is what I ended up doing! Thank you anyhow for the clarification.
