### ISSUE TITLE
Missing sitk.ElastixImageFilter()

### ISSUE THREAD

**Issue by mrceresa** [kaspermarstal/SimpleElastix#86]
Dear Kasper,
thanks for making available SimpleElastix! I cannot access ElastixImageFilter:
```
In [2]: import SimpleITK as sitk
In [3]: sitk.ElastixImageFilter()
AttributeError: 'module' object has no attribute 'ElastixImageFilter'
```
Do I have a corrupted install or did the API changed from the doc? That's because everything else seems to be functional...

Thanks and regards,

Mario

**Comment by kaspermarstal** [comment]
Hi @mrceresa! Yes, the docs have been updated in preparation of the v1.0.0 release (prematurely, I admit). `sitk.ElastixImageFilter()` is `sitk.SimpleElastix()` on the current master branch, and `sitk.TransformixImageFilter()` is `sitk.SimpleTransformix()`.

**Comment by kaspermarstal** [comment]
The master branch has been updated to v1.0.0. `git pull`, recompile, and `ElastixImageFilter` and `TransformixImageFilter` will be available.

**Comment by giacomomarchioro** [comment]
Dear Kasper,

I had the same problem but the proposed solution doesn't work for me.

There is no sitk.SimpleElastix()! In simpleITK-1.0.1 installed in Windows10 using `pip install SimpleITK`


Thansk a lot!

**Comment by PertuyF** [comment]
Hi @giacomomarchioro ,
`SimpleElastix` is not part of the `SimpleITK` package available from pypi. You have to build it from source, as indicated in [the doc](https://simpleelastix.readthedocs.io/GettingStarted.html).

**Comment by giacomomarchioro** [comment]
@PertuyF  Ops sorry I've misunderstood! Thanks for the help!

**Comment by XXZhou25** [comment]
Hi, 

I was wondering if `TransformixImageFilter` or `SimpleTransformix()` only exists in simpleitk 1.0?
I am using simpleitk 2.0.2 which I directly used pip installed but it keeps showing:
`>>> import SimpleITK as sitk
>>> sitk.TransformixImageFilter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'SimpleITK' has no attribute 'TransformixImageFilter'
>>> sitk.SimpleTransformix()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'SimpleITK' has no attribute 'SimpleTransformix'`
