### ISSUE TITLE
Anaconda

### ISSUE THREAD

**Issue by gattia** [kaspermarstal/SimpleElastix#9]
Hi All, 

Has anyone got SimpleElastix working with Anaconda? What approach did you use? 

Anaconda is the current python that my terminal goes to so when setting up SimpleElastix it auto populated all the variables correctly to that python (see the end of post). Then I ran the setup.py and everything seemed to work but when I go to import SimpleITK my python console crashes and I get the error: 
"Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6"

Any thoughts or suggestions? 

Thanks, 

Anthony. 

PYTHON_EXECUTABLE                /Users/gattia/anaconda2/bin/python
 PYTHON_INCLUDE_DIR               /Users/gattia/anaconda2/include/python2.7
 PYTHON_LIBRARY                   /Users/gattia/anaconda2/lib/libpython2.7.dyli
 PYTHON_LIBRARY_DEBUG             PYTHON_LIBRARY_DEBUG-NOTFOUND

**Comment by gattia** [comment]
Just to keep an update. I ended up finding this (https://gist.github.com/kevin-keraudren/849332f1c8f01294cfdb) and another resource that indicated it might be due to the DYLD_FALLBACK_LIBRARY_PATH. So, I added that to my .bash_profile:
 (export DYLD_FALLBACK_LIBRARY_PATH=/Users/gattia/anaconda2/lib:${DYLD_FALLBACK_LIBRARY_PATH}). 

And all is right in the world again :). 

Just replace /Users/gattia/anaconda2/lib with the location to your anaconda library, whether that be in a venv or something else. 

-Anthony.

**Comment by gattia** [comment]
And I spoke too soon. I was able to get SimpleITK imported into the terminal python. But it won't work on iPython in the terminal or in Spyder. Which both come as part of Anaconda. 

I get a fatal python error: 
In [1]: import SimpleITK
Fatal Python error: PyThreadState_Get: no current thread
/Users/gattia/anaconda2/bin/python.app: line 3: 91589 Abort trap: 6           /Users/gattia/anaconda2/python.app/Contents/MacOS/python "$@"

Any suggestions? 

Thanks, 

Anthony.

**Comment by kaspermarstal** [comment]
While I have no experience with your particular issue, [this StackOverflow thread](http://stackoverflow.com/questions/15678153/homebrew-python-on-mac-os-x-10-8-fatal-python-error-pythreadstate-get-no-cu) mentions that it may be due to SimpleElastix linking against system python libraries rather than the Anaconda libraries. 

If this is the case, one solution may be to check the PYTHON_EXECUTABLE, PYTHON_INCLUDE_DIR and PYTHON_LIBRARY CMake variables in the SimpleITK-build directory and change these variables to their Anaconda equivalents.

Might be worth checking out.

**Comment by PertuyF** [comment]
Hi,
I actually use SimpleElastix with anaconda and spyder, but on Windows.
So I can't really help here but to say it should not be related to anaconda or spyder specifically.

**Comment by gattia** [comment]
Thanks for the responses. 

Still having the same issue and it does seem to be with the location or where SimpleElastix thinks the python libraries are. When running the otool -L on _SimpleITK.so which is within the site-packages of anaconda I get a list of libraries including the libpython2.7.dylib but thats it, there is no path ahead of it. I am assuming it should read out "/Users/gattia/anaconda2/lib/libpython2.7.dylib" to actually point to where the library is. 

So, this should be a simple switch that needs to be made in the ccmake within the SimpleElasix build, right? But when I go to the terminal GUI and look for PYTHON_LIBRARY it is pointing to the correct location "/Users/gattia/anaconda2/lib/libpython2.7.dylib" 

I think I can use install_name_tool to rectify this... though I'm still trying to figure out how that works. I will get back with a fix if I can figure it out. 

Anthony.

**Comment by gattia** [comment]
Ok... So it appears to be finally working in iPython and in Spyder. So for some reason the location of the python dylib that was input into cmake was not actually used.... 

To change it. I ran: 
otool -L /Users/gattia/anaconda2/lib/python2.7/site-packages/SimpleITK-0.9.1.dev15-py2.7-macosx-10.5-x86_64.egg/SimpleITK/_SimpleITK.so

From my understanding this gave a list of the dependencies SimpleITK. Here was my output: 

/Users/gattia/anaconda2/lib/python2.7/site-packages/SimpleITK-0.9.1.dev15-py2.7-macosx-10.5-x86_64.egg/SimpleITK/_SimpleITK.so:
	libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1255.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)

The problem was that libpython2.7.dylib did not have a path infront of it. So this needed to be changed. To do this I used install_name_tool using sudo: 

sudo install_name_tool -change libpython2.7.dylib /Users/gattia/anaconda2/lib/libpython2.7.dylib /Users/gattia/anaconda2/lib/python2.7/site-packages/SimpleITK-0.9.1.dev15-py2.7-macosx-10.5-x86_64.egg/SimpleITK/_SimpleITK.so

Essentially that was: 
sudo install_name_tool -change <location it thinks the dylib is in> <location the dylib was actually in> <path to the _SimpleITK.so> 

Then, I re-ran the otool command to make sure it worked and my output was: 
/Users/gattia/anaconda2/lib/python2.7/site-packages/SimpleITK-0.9.1.dev15-py2.7-macosx-10.5-x86_64.egg/SimpleITK/_SimpleITK.so:
	/Users/gattia/anaconda2/lib/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1255.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)

It all works now. Thanks for the responses and hopefully this little goose chase can help someone else. 

Anthony.
