### ISSUE TITLE
TransformixImageFilter or  SimpleTransformix?

### ISSUE THREAD

**Issue by kskwong** [kaspermarstal/SimpleElastix#90]
In the examples for the documentation to use Transformix, they all indicate to use sitk.TransformixImageFilter.  However when I try this, I get the following AttributeError:

>>> tif = sitk.TransformixImageFilter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'SimpleITK' has no attribute 'TransformixImageFilter'

However when I use SimpleTransformix instead, there is no error complaint, e.g.:
>>> tif = sitk.SimpleTransformix()

I'm wondering if these are the same thing and this issue is because the documentation regarding SimpleTransformix is out-of-date? Or am I misunderstanding the use of SimpleTransformix vs TransformixImageFilter, and that possibly something is wrong with my SimpleElastix build?

Thanks.

**Comment by kaspermarstal** [comment]
TransformixImageFilter is the new and correct name. This was changed in the newest release and the docs were updated to reflect this. You have the prior version, so just `git pull` and rebuild for the changes to take effect.

**Comment by kskwong** [comment]
Ah, that explains it, thanks Kasper!
