### ISSUE TITLE
SimpleElastix 3D Rotation Application?

### ISSUE THREAD

**Issue by unimusic** [kaspermarstal/SimpleElastix#91]
Hi,

I have a question regarding applying a user-determined 3D rotation matrix to an entire 3D image. Is there a function in SimpleElastix that allows for this?

Thanks!

- Angela

**Comment by kaspermarstal** [comment]
Yes, you can manually change the `TransformParameters` variable of a transform parameter map and then apply it via Transformix. 

Run an affine registration with `ElastixImageFilter` and use `elastixImageFilter.SetParameterMap(sitk.GetDefaultParameterMap('rigid'))` to get a working transform parameter map. Then you can adjust the transform parameters. The order of the parameters are explained here http://lists.bigr.nl/pipermail/elastix/2010-January/000007.html

**Comment by unimusic** [comment]
Right now, I'm using sitk.VersorTransform() and setting the rotation to get a rotation matrix. I am not trying to register two images. Is there any way to use the rotation matrix to rotate my image without creating a parameter map? Thanks!

**Comment by unimusic** [comment]
I am trying to rotate an image without registering it to another image. Instead, I am trying to specify a rotation matrix. Is this possible? If so, how? Thanks!

**Comment by kaspermarstal** [comment]
Yes that is possible. The registration outlined above is only to get a "template" of a transform parameter map that you can tweak yourself. No need to run it every time. After you have your "template", you can adjust the `TransformParameters` setting to your heart's content and warp as many images as your like. 

The affine `TransformParameters` contain parameters [p1, ..., p12] of the affine transform: the first 9 are the rotation matrix in row order, the last 3 the translation. So,

	T(x) = Ax + t 

where `t` is the translation vector 

    [ p10 p11 p12 ]^T

and `A` is the rotation matrix,

    [ p1 p2 p3 
      p4 p5 p6 
      p7 p8 p9 ]

Be default the image is rotated around the image origin. To specify another point, you can use the "CenterOfRotationPoint" found in the transform parameters file. The equation then becomes 

    T(x) = A ( x - c ) + t + c

where `c` is the center of rotation which is specified in "CenterOfRotationPoint". 

Note that all parameters have to be specified as strings. For example, the identity transform is specified like this: 

    p[0]['TransformParamerters'] = ['1', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0']

**Comment by unimusic** [comment]
Thanks, that seems to work. However, the rotated image using this method always has the same size as the original image. Is there a parameter I can change to get rid of this constraint?

**Comment by kaspermarstal** [comment]
You multiply the rotation matrix with a constant to change the scale of the transformed image. For example, if you want to make the image twice as large, you multiply all rotation parameters with 2.

**Comment by unimusic** [comment]
I understand the scaling, but it seems that the choice of a fixed and moving image limits the scope of the points that can be represented in the rotated matrix. For example, if I want to translate my image by 100 voxels in the x direction, they won't show up. Is this right?

**Comment by kaspermarstal** [comment]
Sorry, but there is too little information to tell you what is right or wrong. You have to post working code to get such detailed answers :)

In general, the field of view is limited to that of the fixed image, so if you new points are transformed to an area outside the fixed image world field of view, they will be lost. If you want to just reorient dimensions, you can achieve this without an explicit transformation by using `GetDirection()` and `SetDirection()` on the image.

**Comment by unimusic** [comment]
Okay, I see. I will see what I can do. Thanks Kasper :)
